import {
  GraduationCap,
  Database,
  BarChart3,
  LayoutDashboard,
  Users,
  Repeat,
  LineChart,
  CheckSquare,
  Monitor,
  ShieldCheck,
  Workflow,
  ClipboardList,
  Handshake,
  BookOpen,
  Briefcase,
  Settings,
  TrendingUp,
  FileText,
  Gauge,
  History,
  MapPin,
  Mail,
  Share2,
  Lock,
  Wrench,
  Terminal,
  CheckCircle2,
  Hourglass,
  Send,
  Download,
  ChevronDown,
  Menu,
  X,
  ArrowRight,
  Eye,
  Clock,
  Cpu,
  Sparkles,
  Package,
  Image as ImageIcon,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  "graduation-cap": GraduationCap,
  database: Database,
  "bar-chart-3": BarChart3,
  "layout-dashboard": LayoutDashboard,
  users: Users,
  repeat: Repeat,
  "line-chart": LineChart,
  "check-square": CheckSquare,
  monitor: Monitor,
  "shield-check": ShieldCheck,
  workflow: Workflow,
  "clipboard-list": ClipboardList,
  handshake: Handshake,
  "book-open": BookOpen,
  briefcase: Briefcase,
  settings: Settings,
  "trending-up": TrendingUp,
  "file-text": FileText,
  gauge: Gauge,
  history: History,
  "map-pin": MapPin,
  mail: Mail,
  share: Share2,
  lock: Lock,
  wrench: Wrench,
  terminal: Terminal,
  "check-circle": CheckCircle2,
  hourglass: Hourglass,
  send: Send,
  download: Download,
  "chevron-down": ChevronDown,
  menu: Menu,
  x: X,
  "arrow-right": ArrowRight,
  eye: Eye,
  clock: Clock,
  cpu: Cpu,
  sparkles: Sparkles,
  package: Package,
  image: ImageIcon,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? CheckSquare;
}
